apiVersion: apps/v1
kind: Deployment
metadata:
  name: cgp-master
  namespace: cgp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cgp-master
  template:
    metadata:
      labels:
        app: cgp-master
    spec:
      containers:
      - name: master
        image: cgp-nt-again:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 2727
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        command: ["sh", "scripts/run_naut_eval.sh"]
        env:
        - name: IN_DOCKER_COMPOSE
          value: "1"
        - name: WHERE_IS_RABBIT
          value: "cgp-rabbitmq"
        - name: RMQ_USER
          valueFrom:
            secretKeyRef:
              name: cgp-secrets
              key: rabbitmq-user
        - name: RMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cgp-secrets
              key: rabbitmq-pass
        volumeMounts:
        - name: condorgp-volume-alembic
          mountPath: /condorgp/alembic
        - name: condorgp-volume-cgp-db
          mountPath: /condorgp/cgp_db
        - name: condorgp-volume-cgp-rabbitmq
          mountPath: /condorgp/cgp_rabbitmq
        - name: condorgp-volume-condorgp
          mountPath: /condorgp/condorgp
        - name: condorgp-volume-data
          mountPath: /condorgp/data
        - name: condorgp-volume-raw-data
          mountPath: /condorgp/raw_data
        - name: condorgp-volume-scripts
          mountPath: /condorgp/scripts
        - name: condorgp-volume-tests
          mountPath: /condorgp/tests
      volumes:
      - name: condorgp-volume-alembic
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/alembic

      - name: condorgp-volume-cgp-db
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/cgp_db

      - name: condorgp-volume-cgp-rabbitmq
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/cgp_rabbitmq

      - name: condorgp-volume-condorgp
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/condorgp

      - name: condorgp-volume-data
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/data

      - name: condorgp-volume-raw-data
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/raw-data

      - name: condorgp-volume-scripts
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/scripts
          
      - name: condorgp-volume-tests
        hostPath:
          path: /home/hsth/code/hughharford/condorgp/tests




---
apiVersion: v1
kind: Service
metadata:
  name: cgp-master
  namespace: cgp-system
spec:
  selector:
    app: cgp-master
  ports:
  - port: 2727
    targetPort: 2727
